const Types = {
  SET_CITIES_COUNT: 'SET_CITIES_COUNT',
  SET_PROFFESORS_COUNT: 'SET_PROFFESORS_COUNT',
  SET_STUDENTS_COUNT: 'SET_STUDENTS_COUNT',
  SET_GROUPS_COUNT: 'SET_GROUPS_COUNT',
};

export default Types;