const Types = {
  FETCH_CITIES_START: 'FETCH_CITIES_START',
  FETCH_CITIES_SUCCESS: 'FETCH_CITIES_SUCCESS',
  FETCH_CITIES_FAILURE: 'FETCH_CITIES_FAILURE',
  ADD_CITIES_START: 'ADD_CITIES_START',
  ADD_CITIES_SUCCESS: 'ADD_CITIES_SUCCESS',
  ADD_CITIES_FAILURE: 'ADD_CITIES_FAILURE',
  DELETE_CITIES_SUCCESS: 'DELETE_CITIES_SUCCESS',
  EDIT_CITIES_SUCCESS: 'EDIT_CITIES_SUCCESS',
};

export default Types;