const Types = {
  FETCH_GROUPS_START: 'FETCH_GROUPS_START',
  FETCH_GROUPS_SUCCESS: 'FETCH_GROUPS_SUCCESS',
  FETCH_GROUPS_FAILURE: 'FETCH_GROUPS_FAILURE',
  ADD_GROUPS_START: 'ADD_GROUPS_START',
  ADD_GROUPS_SUCCESS: 'ADD_GROUPS_SUCCESS',
  ADD_GROUPS_FAILURE: 'ADD_GROUPS_FAILURE',
  DELETE_GROUPS_SUCCESS: 'DELETE_GROUPS_SUCCESS',
  EDIT_GROUPS_SUCCESS: 'EDIT_GROUPS_SUCCESS',
  GET_GROUP_STUDENTS: 'GET_GROUP_STUDENTS',
};

export default Types;