const Types = {
  FETCH_MEMBERS_START: 'FETCH_MEMBERS_START',
  FETCH_MEMBERS_SUCCESS: 'FETCH_MEMBERS_SUCCESS',
  FETCH_MEMBERS_FAILURE: 'FETCH_MEMBERS_FAILURE',
  ADD_MEMBERS_START: 'ADD_MEMBERS_START',
  ADD_MEMBERS_SUCCESS: 'ADD_MEMBERS_SUCCESS',
  ADD_MEMBERS_FAILURE: 'ADD_MEMBERS_FAILURE',
  DELETE_MEMBERS_SUCCESS: 'DELETE_MEMBERS_SUCCESS',
  EDIT_MEMBERS_SUCCESS: 'EDIT_MEMBERS_SUCCESS',
};

export default Types;